[project]
name = "nostr-ai"
version = "0.1.0"
description = "Decentralized AI agent using NOSTR and MCP"
requires-python = ">=3.11"
dependencies = [
    "nostr-agent-tools>=0.4.6",
    "langchain-nostr-mcp-adapters>=0.0.2",
    "fastapi>=0.115.12",
    "langchain-anthropic>=0.3.13",
    "langgraph>=0.4.3",
    "pynostr>=0.6.2",
    "uvicorn>=0.34.2",
]

[tool.uv]
reinstall-package = ["langchain-nostr-mcp-adapters", "nostr-agent-tools"]
