[project]
name = "nostr-ai"
version = "0.1.0"
description = "Decentralized AI agent using NOSTR and MCP"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.12",
    "langchain-anthropic>=0.3.13",
    "langchain-mcp-adapters",
    "langgraph>=0.4.3",
    "nostr-agent-tools>=0.3.4",
    "pynostr>=0.6.2",
    "uvicorn>=0.34.2",
]

[tool.uv.sources]
langchain-mcp-adapters = { git = "https://github.com/ehallmark/langchain-mcp-adapters", rev = "nostr" }

[tool.uv]
reinstall-package = ["langchain-mcp-adapters"]
